#SPDX-License-Identifier: MIT-0
---
# tasks file for deploy
- name: Pull an image
  community.docker.docker_image_pull:
    name: "{{ image_name }}"

- name: Start a container
  community.docker.docker_container:
      name: project-devops-deploy
      image: "{{ image_name }}"
      state: started
      restart_policy: always
      ports:
        - "8080:8080"
      env:
        SPRING_PROFILES_ACTIVE: "prod"
        SPRING_DATASOURCE_URL: "jdbc:postgresql://rc1a-knp27jjb37mp8r82.mdb.yandexcloud.net:6432/db1?targetServerType=master&sslmode=require"
        SPRING_DATASOURCE_USERNAME: "{{ SPRING_DATASOURCE_USERNAME }}"
        SPRING_DATASOURCE_PASSWORD: "{{ SPRING_DATASOURCE_PASSWORD }}"
        STORAGE_S3_ACCESSKEY: "YCAJEgsS3AeHlDIbQd_pcoL1O"
        STORAGE_S3_SECRETKEY: "{{ STORAGE_S3_SECRETKEY }}"
        STORAGE_S3_REGION: "ru-central1"
        STORAGE_S3_BUCKET: "prod-users-files"
        STORAGE_S3_ENDPOINT: "https://storage.yandexcloud.net"