- hosts: all
  become: true
  roles:
    - role: geerlingguy.docker
  tasks:
    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ docker_user }}"
        create_home: true
        shell: /bin/bash
        groups: docker
        append: true

    - name: UFW allow SSH
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: UFW allow HTTP
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: UFW allow HTTPS
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp

    - name: UFW allow 8080
      community.general.ufw:
        rule: allow
        port: '8080'
        proto: tcp

    - name: Deny everything and enable UFW
      community.general.ufw:
        policy: deny
        state: enabled