- hosts: all
  become: true
  roles:
    - role: geerlingguy.docker
    - role: geerlingguy.nginx
      vars:
        nginx_proxy_cache_path: "/var/cache/nginx keys_zone=my_cache:10m inactive=60m max_size=1g"

  tasks:
    - name: Remove default Nginx vhost
      ansible.builtin.file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Copy nginx conf file to remote host
      ansible.builtin.copy:
        src: files/my_domain.conf   
        dest: /etc/nginx/conf.d/my_domain.conf
        owner: root
        group: root
        mode: '0644'
      notify: Nginx reload

    - name: Add user to docker group
      ansible.builtin.user:
        name: "{{ docker_user }}"
        create_home: true
        shell: /bin/bash
        groups: docker
        append: true

    - name: UFW allow SSH
      community.general.ufw:
        rule: allow
        port: '22'
        proto: tcp

    - name: UFW allow HTTP
      community.general.ufw:
        rule: allow
        port: '80'
        proto: tcp

    - name: UFW allow HTTPS
      community.general.ufw:
        rule: allow
        port: '443'
        proto: tcp

    - name: Deny everything and enable UFW
      community.general.ufw:
        policy: deny
        state: enabled
    
  handlers:
    - name: Nginx reload
      service:
        name: nginx
        state: reloaded
